name: Setup Node and Install Deps
description: Reusable Node setup amd install dependencies
runs:
  using: "composite"
  steps:
      # Set up Node.js with specific version
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.13.1'
      
      # Install a specific version of pnpm
      - name: Instalação do PNPM@9.6.0
        uses: pnpm/action-setup@v4.0.0
        with:
          version: '9.6.0'
        
      # Install dependencies
      - name: Instalar dependências
        run: pnpm install

