name: Configura commit
description: Reusable configuration commit
runs:
  using: "composite"
  steps:
      - name: Configurar Git
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
