name: Master PRs

on:
  pull_request:
    branches: [master]  

jobs:
  check:
    runs-on: ubuntu-latest
    
    outputs:
      format-failed: ${{ steps.format-check.outcome == 'failure' }}

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node and Install Deps
        uses: './.github/workflows/actions/setup-node-install-deps' 
            
      # Run Check
      - name: Executar Check
        id: format-check
        run: pnpm check
        continue-on-error: true

      - name: Erro de formatação é ou lint
        if: steps.format-check.outcome == 'failure'
        run: exit 1


  teste:
    runs-on: ubuntu-latest
    needs: check

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node and Install Deps
        uses: './.github/workflows/actions/setup-node-install-deps' 
            
      # Run tests
      - name: Executar testes
        run: pnpm jest

  format:
    runs-on: ubuntu-latest
    needs: check
    
    if: needs.check.result == 'failure'   # roda só se o check falhar
    
    steps:
      - name: Mostrar mensagem no log
        run: echo "Olá, isso aparece no console do GitHub Actions"
      
      
