name: Master PRs

on:
  pull_request:
    branches: [master]  

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node and Install Deps
        uses: './.github/actions/setup-node-install-deps' 
            
      # Run tests
      - name: Executar Check
        run: pnpm check

  teste:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node and Install Deps
        uses: './.github/actions/setup-node-install-deps' 
            
      # Run tests
      - name: Executar testes
        run: pnpm jest

      
