name: Master PRs

on:
  pull_request:
    branches: [master]  

jobs:
  check:
    runs-on: ubuntu-latest
    
    outputs:
      format-failed: ${{ steps.format-check.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
      
      - uses: './.github/workflows/actions/setup-node-install-deps' 
          
      - name: Executar Check
        id: format-check
        run: pnpm check
        continue-on-error: true

      - name: Erro de formatação é ou lint
        if: steps.format-check.outcome  == 'failure'
        run: exit 1
    
  approval:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.conclusion == 'success'
    environment: approval  # pausa até aprovação
    steps:
      - run: echo "Aguardando aprovação para continuar..."
        
  format:
    runs-on: ubuntu-latest
    needs: approval
    
    steps:
      - name: Mostrar mensagem no log
        run: echo "Olá, isso aparece no console do GitHub Actions"
        
  teste:
    runs-on: ubuntu-latest
    needs: check

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node and Install Deps
        uses: './.github/workflows/actions/setup-node-install-deps' 
            
      # Run tests
      - name: Executar testes
        run: pnpm jest
      
