name: Testes

on:
  push:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node and Install Deps
        uses: './.github/workflows/actions/setup-node-install-deps' 
            
      # Run tests
      - name: Executar testes
        run: pnpm jest

      
