name: Atualizar Documentação

on: 
    push:
        branches:
            - master
        
jobs:
  teste:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node and Install Deps
        uses: './.github/actions/setup-node-install-deps' 

      # Run tests
      - name: Executar testes
        run: pnpm jest
        
  update-doc:
    needs: teste  # Só executa se os testes passarem
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node and Install Deps
        uses: './.github/actions/setup-node-install-deps' 
        
      - name: Executar testes
        run: pnpm test

      - name: Atualizar documentação
        run: node update-doc.js
      
      - name: Checkout branch 'doc'
        run: |
            git checkout -b doc
        
      - name: Commit e 
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add EXPLORATION.md
          git commit -m ":memo: Atualizando documentação automática" || echo "Nenhuma alteração para commit"
      
      - name: Push das mudanças
        run: |
            git push --set-upstream origin doc
      
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
